Algoritmo "jonas"
// Disciplina   : [Lógica de Programação Visualg]
// Professor   : Jailson costa
// Descrição   : explicação de loop enquanto
// Autor(a)    : Jonas H.
// Data atual  : 24/03/2025
Var
   // Seção de Declarações das variáveis
   contador:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   enquanto contador<10 faca
      escreval("Jonas")
      contador<- contador + 1
   fimenquanto
Fimalgoritmo