Algoritmo "pares"
// Disciplina   : [Lógica de Programação Visualg]
// Professor   : Jailson costa
// Descrição   : mostra os pares entre 2 até 20
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/04/2025
Var
   // Seção de Declarações das variáveis
   numero:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   enquanto numero < 20 faca
      numero <- numero + 2
      escreva(numero)
   fimenquanto

Fimalgoritmo